Adds Support for Swift Package Manager
rolandleth/LTHPasscodeViewController pull request #208
Opened 2021-03-27 15:36 UTC by jaerod95

Adds support for SPM. See README.md for instructions on how to add it to your project.

Finally got around to fixing this up again. Now that Apple supports Resources I was able to import the Localizations. I added to the LTHPasscodeViewControllerStrings method to search for the SPM bundle if it didn't find a localized string since Apple moves those localizations into its own bundle.

2021-03-29 07:15 UTC, rolandleth requested changes
Thank you for the contribution! Just a few changes to be made, please.

Also, could you please explain a bit the need for the `LTHPasscodeViewControllerStrings` change? Haven't worked with SPM yet, so no idea what the issue was and how it got solved.

2021-03-29 15:02 UTC, jaerod95 commented on LTHPasscodeViewController/LTHPasscodeViewController.m
> +[[[NSBundle bundleWithPath:[[NSBundle bundleForClass:[LTHPasscodeViewController class]] pathForResource:@"LTHPasscodeViewController" ofType:@"bundle"]] localizedStringForKey:(key) value:@"" table:_lo
Love this idea. To be honest my Objc experience is basically none, so I was kinda just shooting in the dark here to make it work 😅 I'll make the change.

2021-03-29 15:08 UTC, jaerod95 commented on Package.swift
> +            exclude: ["Demo", "CHANGELOG.md", "LICENSE.txt", "README.md"],
This doesn't stop it from being shown when it's used in the side bar, but just doesn't compile it into the package binary. If that's still a problem I can process it into the bundle I believe.
<img width="377" alt="Screen Shot 2021-03-29 at 8 08 00 AM" src="https://user-images.githubusercontent.com/19922122/112857614-e3084a00-9065-11eb-8a07-05b7f7313fd8.png">

2021-03-29 15:37 UTC, rolandleth commented on Package.swift
> +            exclude: ["Demo", "CHANGELOG.md", "LICENSE.txt", "README.md"],
Hmm, I usually include license files in apps (even create About pages to display the full license text), so if it's possible, without breaking anything, that would be nice 👍

2021-03-29 17:22 UTC, jaerod95 commented on README.md
> +### Swift Package Manager
Done

2021-03-29 17:22 UTC, jaerod95 commented on README.md
> +[CocoaPods](https://cocoapods.org) is a dependency manager for Cocoa projects. For usage and installation instructions, visit their website. To integrate LTHPasscodeViewController into your Xcode pro
Done

2021-03-29 17:22 UTC, jaerod95 commented on README.md
> +2. Paste the URL to the LTHPasscodeViewController repo on GitHub (https://github.com/rolandleth/LTHPasscodeViewController.git) into the search bar, then hit the Next button:
Done

2021-03-29 17:23 UTC, jaerod95 commented on Package.swift
> +            exclude: ["Demo", "CHANGELOG.md", "LICENSE.txt", "README.md"],
Sounds great I'll make the change.

2021-03-29 17:24 UTC, jaerod95 commented on Package.swift
> +            sources: ["LTHPasscodeViewController/LTHKeychainUtils.h", "LTHPasscodeViewController/LTHKeychainUtils.m", "LTHPasscodeViewController/LTHPasscodeViewController.h", "LTHPasscodeViewControll
This actually wasn't needed so I just removed the line.

2021-03-29 17:24 UTC, jaerod95 commented on LTHPasscodeViewController/LTHPasscodeViewController.m
> +[[[NSBundle bundleWithPath:[[NSBundle bundleForClass:[LTHPasscodeViewController class]] pathForResource:@"LTHPasscodeViewController" ofType:@"bundle"]] localizedStringForKey:(key) value:@"" table:_lo
Updated to use your snippet. Worked great!

2021-03-29 17:24 UTC, jaerod95 commented on README.md
> + @param    viewController The view controller where the passcode view controller will be displayed.
Done

2021-03-29 17:26 UTC, jaerod95 commented
The reason I needed to change the LTHPasscodeViewControllerStrings was due to how the new SPM tooling processes resources. Basically it compiles them into a bundle and exposes that bundle to Swift and Objc. I gathered most of my information on what that looks like from this article: https://darjeelingsteve.com/articles/How-to-Use-Module-Resources-in-Objective-C-SPM-Packages.html

2021-03-29 17:57 UTC, rolandleth commented
Thanks for sharing the article! 

Hmm, is there any way to test the package before merging? Can I add it to a project by entering the URL of your `dev` branch? Not sure what the syntax would be, maybe https://github.com/SimpleNexus/LTHPasscodeViewController/tree/dev?

2021-04-02 08:35 UTC, rolandleth commented on Package.swift
> +            exclude: ["Demo", "CHANGELOG.md", "LICENSE.txt", "README.md"],
I think this is the only thing remaining, right?

2021-04-08 17:17 UTC, jaerod95 commented
> Thanks for sharing the article!
> 
> Hmm, is there any way to test the package before merging? Can I add it to a project by entering the URL of your `dev` branch? Not sure what the syntax would be, maybe https://github.com/SimpleNexus/LTHPasscodeViewController/tree/dev?

Yes! You can simply add https://github.com/SimpleNexus/LTHPasscodeViewController as the git source, then on the rules page, just select branch and point it at dev as seen in the picture below:
![Screen Shot 2021-04-08 at 10 16 45 AM](https://user-images.githubusercontent.com/19922122/114069161-879f3e80-9853-11eb-9961-9d5aa335d6ac.png)

2021-04-08 17:21 UTC, jaerod95 commented on Package.swift
> +            exclude: ["Demo", "CHANGELOG.md", "LICENSE.txt", "README.md"],
Yup, just updated the package.swift to now process the `LICENSE.txt` file.

2021-04-10 05:48 UTC, rolandleth commented
Cool, I'll give it a go today, thanks!

2021-04-17 09:16 UTC, rolandleth commented
Hey! Very sorry for the long delay, but I managed to give it a go today. I added the package to a Swift project and everything works, except localization. Maybe I'm not doing it properly, but I set the project to use English and German, I added a `Localizable.strings` file, but the passcode view isn't localized.

Either I'm doing something wrong, or the macro isn't working properly 🤔🤔 Can you get localization to work when using the passcode as a package?

The demo project is properly localized.

2021-12-06 16:58 UTC, jaerod95 commented
@rolandleth Sorry for the delay, got distracted for a quick....8 months haha. However I updated the code to work with localization (nice catch by the way). There was an issue where I was looking in the wrong bundle The last two commits fix that. Let me know if there are any other issues.

2024-04-12 06:05 UTC, rolandleth approved these changes

2024-04-12 06:15 UTC, rolandleth commented
@jaerod95 This has to be the slowest moving PR in history 🙈 I tested it and it works, I think it's good to merge, thank you!

2024-04-12 06:19 UTC, merged